# GIT alias
alias dots='git --git-dir=$HOME/.dots.git/ --work-tree=$HOME'
alias ga='git add'
alias gb='git branch'
alias gc='git checkout'
alias gcl='git clone --recursive'
alias gd='git diff'
alias gf='git reflog'
alias gl='git log'
alias gld='git log --graph --all --format=format:"%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(bold white)— %an%C(reset)%C(bold yellow)%d%C(reset)" --abbrev-commit --date=relative'
alias gm='git commit -m'
alias gma='git commit -am'
alias gp='git push'
alias gpu='git pull'
alias gra='git remote add'
alias grr='git remote rm'
alias gs='git status -sb'
alias gta='git tag -a -m'
